apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hush.staticSecret.secretName }}
  namespace: {{ .Values.hush.namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  secret: {{ .Values.hush.staticSecret.value | quote }}
---
apiVersion: am.hush.security/v1alpha1
kind: AccessCredential
metadata:
  name: {{ .Values.hush.staticSecret.credentialName }}
  namespace: {{ .Values.hush.namespace }}
spec:
  name: {{ .Values.hush.staticSecret.credentialName }}
  type: plaintext
  description: Static secret for validating non-dynamic secret injection
  secretRef:
    name: {{ .Values.hush.staticSecret.secretName }}
---
apiVersion: am.hush.security/v1alpha1
kind: AccessPolicy
metadata:
  name: {{ .Values.hush.staticSecret.policyName }}
  namespace: {{ .Values.hush.namespace }}
spec:
  name: {{ .Values.hush.staticSecret.policyName }}
  description: Inject static secret into setup demo-app python client
  enabled: true
  accessCredentialRef:
    name: {{ .Values.hush.staticSecret.credentialName }}
  attestationCriteria:
    - type: "k8s:ns"
      value: {{ .Release.Namespace }}
    - type: "k8s:sa"
      value: {{ include "hush-am-demo-app.serviceAccountName" . }}
    - type: "k8s:container-name"
      value: python-client
  deliveryConfig:
    type: env
    config:
      items:
        - name: STATIC_SECRET
          key: data
          type: key
