apiVersion: v1
kind: Service
metadata:
  name: {{ include "hush-am-demo-app.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hush-am-demo-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "hush-am-demo-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: postgres
      protocol: TCP
