nameOverride: ""
fullnameOverride: "hush-am-demo-app"

serviceAccount:
  create: true
  name: ""

pod:
  name: ""

postgres:
  image: postgres:16
  dbName: goatdb
  rootUsername: postgres
  rootPassword: "postgres-demo-root-password"
  port: 5432

pythonClient:
  image:
    repository: public.ecr.aws/z0t8l6o4/hush-k8s-am-demo-app
    tag: main
    pullPolicy: Always
  pollIntervalSeconds: 15

hush:
  namespace: hush-security

  postgresCredential:
    name: hush-am-demo-app-postgres
    privilegeName: hush-am-demo-app-postgres-read
    policyName: hush-am-demo-app-dynamic-policy
    # Host as seen by Hush UAM API (service DNS)
    host: ""
    sslMode: disable

  staticSecret:
    secretName: hush-am-demo-app-static-secret
    credentialName: hush-am-demo-app-static
    policyName: hush-am-demo-app-static-policy
    value: "demo-static-secret"
